- name: Check the current version of Docker Compose
  command: docker-compose --version
  register: current_version
  failed_when: current_version.rc != 0
  ignore_errors: yes

- name: Extract current Docker Compose version
  set_fact:
    current_docker_compose_version: "{{ current_version.stdout.split(' ')[2] }}"
  when: current_version.stdout is defined

- name: Fetch the latest version of Docker Compose
  uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    return_content: yes
  register: latest_version_info
  failed_when: latest_version_info.status != 200

- name: Set latest Docker Compose version
  set_fact:
    latest_version: "{{ latest_version_info.json.tag_name }}"
  when: latest_version_info.content is defined

- name: Compare Docker Compose versions
  debug:
    msg: "Current version: {{ current_docker_compose_version }}, Latest version: {{ latest_version }}"
  when: current_docker_compose_version != latest_version

- name: Download latest Docker Compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ latest_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose.latest
    mode: '0755'
  when: current_docker_compose_version != latest_version

- name: Replace old Docker Compose binary
  copy:
    remote_src: yes
    src: /usr/local/bin/docker-compose.latest
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  when: current_docker_compose_version != latest_version

- name: Remove temporary binary file
  file:
    path: /usr/local/bin/docker-compose.latest
    state: absent
  when: current_docker_compose_version != latest_version

- name: Validate updated Docker Compose version
  command: docker-compose --version
  register: new_version
  when: current_docker_compose_version != latest_version

- name: Display updated Docker Compose version
  debug:
    msg: "Docker Compose successfully updated to {{ new_version.stdout.split(' ')[2] }}"
  when: current_docker_compose_version != latest_version
