# roles/xen_orchestra/tasks/docker_pull.yml

# Pull Docker images as defined in docker-compose.yml
- name: Pull Docker images as defined in docker-compose.yml
  community.docker.docker_compose_v2:
    project_src: /home/paul/docker-compose
    state: present
    pull: always
  register: docker_pull_result
  ignore_errors: yes  # Continue playbook execution even if Docker pull fails

# Display the result of Docker pull
- name: Display the result of Docker pull
  debug:
    var: docker_pull_result

# Check if Docker pull was successful
- name: Check if Docker pull was successful
  fail:
    msg: "Docker pull failed. Please check the logs for details."
  when: docker_pull_result.failed

# Restart Docker services if images were pulled
- name: Restart Docker services if images were pulled
  community.docker.docker_compose_v2:
    project_src: /home/paul/docker-compose
    state: present
    recreate: always  # Recreate containers to use the latest pulled images
  when: docker_pull_result.changed  # Only restart services if images were pulled
