- name: Install Docker prerequisites
  ansible.builtin.include_role:
    name: software_management
    tasks_from: software_install
  vars:
    software_list: "{{ docker_prerequisites }}"
    update_cache: yes

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker-archive-keyring.gpg
    mode: '0644'

- name: Add Docker's APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker Engine
  ansible.builtin.include_role:
    name: software_management
    tasks_from: software_install
  vars:
    software_list: "{{ docker_software }}"
    update_cache: yes

- name: Download latest Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Verify Docker Compose version
  ansible.builtin.command: docker-compose --version
  register: docker_compose_version

- name: Display Docker Compose version
  ansible.builtin.debug:
    msg: "Docker Compose version: {{ docker_compose_version.stdout }}"
