---
# Include individual tasks based on conditions
# Set all to False by default so only run when specifically called  
- name: Include docker_pull tasks
  include_tasks: docker_pull.yml
  when: docker_pull | default(false)
  
- name: Include Check update docker compose
  include_tasks: check_update_docker_compose.yml
  when: check_update_docker_compose | default(false)
  
  - name: Include Check update docker compose
  include_tasks: docker_install.yml
  when: docker_install | default(false)
  
  
  