---
- name: Schedule Playbook Execution
  hosts: workstations
  become: yes

  vars:
    create_cron_playbook: true
    cron_playbook_name: software_dist_update
    cron_playbook_minute: "30"
    cron_playbook_hour: "4"
    cron_playbook_day: "*"
    cron_playbook_month: "*"
    cron_playbook_weekday: "0"
    cron_playbook_command: "ansible-playbook /home/paul/ansible/software_dist_upgrade.yml"

  roles:
    - file_management