---
- name: Schedule Playbook Execution
  hosts: workstations
  become: yes

  vars:
    create_cron_playbook: true
    cron_playbook_name: software_update
    cron_playbook_minute: "19"                  # Minute to run
    cron_playbook_hour: "4,13,16,20"           # Hours to run
    cron_playbook_day: "*"                      # Every day
    cron_playbook_month: "*"                    # Every month
    cron_playbook_weekday: "*"                  # Every weekday
    cron_playbook_command: "software_update.yml" # Just the playbook filename

  roles:
    - file_management