---
# Initial Configuration for new build Ubuntu Servers

- name: Disable IPv6
  hosts: all
  become: true
  tasks:
    - name: Check if IPv6 is enabled
      ansible.builtin.command: sysctl net.ipv6.conf.all.disable_ipv6
      register: ipv6_status

    - name: Disable IPv6
      ansible.builtin.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        state: present
      when: ipv6_status.stdout == 'net.ipv6.conf.all.disable_ipv6 = 0'

    - name: Persist IPv6 disable
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: 'net.ipv6.conf.all.disable_ipv6 = 1'
        state: present
      when: ipv6_status.stdout == 'net.ipv6.conf.all.disable_ipv6 == 0'

    - name: Reload sysctl
      ansible.builtin.command: sysctl -p
      when: ipv6_status.stdout == 'net.ipv6.conf.all.disable_ipv6 == 0'
