---
# This Ansible playbook performs the following tasks:
# - Pulls Docker images defined in the docker-compose.yml file using Docker Compose v2 on all servers in the docker_servers group.

- name: Pull Docker images using Docker Compose v2
  hosts: docker_servers
  become: yes
  tasks:
    - name: Pull images defined in docker-compose.yml
      community.docker.docker_compose_v2:
        project_src: /home/paul/docker-compose
        state: present
        pull: always
