---
# This Ansible playbook updates software and performs group-specific tasks:
#
# This playbook pulls updated Docker images and restarts containers only if needed.

- name: Verify versions of Docker environment
  hosts: docker_servers
  become: yes
  vars:
    verify_versions: true
  roles:
    - role: docker_management