---
- name: Update Docker Environment
  hosts: docker_servers
  become: yes
  vars:
    verify_versions: true
    remove_old_versions: false
    install_docker: false
    install_docker_compose: false
    install_docker_plugin: false
    update_docker: true
    update_docker_compose: true
    update_docker_plugin: true
    pull_containers_and_restart: false

  roles:
    - role: docker_management