---
# This Ansible playbook updates software and performs group-specific tasks:
#
# This playbook pulls updated Docker images and restarts containers only if needed.

- name: Pull Docker images and restart containers if updated
  hosts: docker_servers
  strategy: free
  become: yes
  vars:
    pull_containers_and_restart: true
  roles:
    - role: docker_management