---
- name: Firewall status
  hosts: all
  become: true
  tasks:
    - name: Check firewall status
      ansible.builtin.shell: sudo ufw status
      register: ufw_status

    - name: Display firewall status and rules
      ansible.builtin.debug:
        msg: "{{ ufw_status.stdout_lines }}"
