---
# Initial Configuration for new build Ubuntu Servers

- name: Install packages and configure servers
  hosts: all
  become: true
  tasks:

    - name: Check disk space
      ansible.builtin.debug:
        var: my_secret
  
    # Install Core Apps
    - name: Install aptitude and cockpit
      tags: 
        - ubuntu
        - aptitude
        - cockpit
      ansible.builtin.apt:
        name: 
          - aptitude
          - cockpit
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]
    
    # Setup Swap file
    - name: Check if swap file exists
      tags:
        - ubuntu
      ansible.builtin.stat:
        path: /swapfile
      register: swapfile_exists

    - name: Create swap file
      ansible.builtin.command: fallocate -l 4G /swapfile
      when: not swapfile_exists.stat.exists

    - name: Set swap file permissions
      ansible.builtin.file:
        path: /swapfile
        mode: '0600'
      when: not swapfile_exists.stat.exists

    - name: Make swap file
      ansible.builtin.command: mkswap /swapfile
      when: not swapfile_exists.stat.exists

    - name: Enable swap file
      ansible.builtin.command: swapon /swapfile
      when: not swapfile_exists.stat.exists

    - name: Add swap to fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: '/swapfile none swap sw 0 0'
        create: yes
      when: not swapfile_exists.stat.exists
    
    - name: Check the current timezone
      ansible.builtin.command: timedatectl show -p Timezone --value
      register: current_timezone

    - name: Set timezone to Europe/London
      ansible.builtin.command: timedatectl set-timezone Europe/London
      when: current_timezone.stdout != 'Europe/London'

    # Disable IPv6
    - name: Check if IPv6 is enabled
      ansible.builtin.command: sysctl net.ipv6.conf.all.disable_ipv6
      register: ipv6_status

    - name: Disable