---
# This Ansible playbook performs the following tasks:
# - Checks if a reboot is required by looking for the presence of the /var/run/reboot-required file.
# - Displays a message indicating whether a reboot is necessary or not.

- name: Check Reboot Requirement Playbook
  hosts: all
  become: yes
  tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Show reboot result
      debug:
        msg: >
          {% if reboot_required_file.stat.exists %}
            A reboot is required.
          {% else %}
            No reboot is necessary.
          {% endif %}
