---
- name: Check Reboot Requirement Playbook
  hosts: all
  become: yes
  tasks:

  - name: Check if reboot is required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file
    
  - name: Reboot if necessary
    reboot:
    when: reboot_required_file.stat.exists
    
    
