---
- name: Check Reboot Requirement Playbook
  hosts: all
  become: yes
  tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Show reboot result
      debug:
        msg: >
          {% if reboot_required_file.stat.exists %}
            A reboot is required.
          {% else %}
            No reboot is necessary.
          {% endif %}
