---
- name: Update APT cache and perform a safe upgrade using software_Management role
  hosts: all
  become: yes

  tasks:
    - name: Include apt_cache task
      ansible.builtin.include_tasks: roles/software_management/tasks/apt_cache.yml

    - name: Include safe_upgrade task
      ansible.builtin.include_tasks: roles/software_management/tasks/safe_upgrade.yml
