---
# This Ansible playbook performs the following tasks:
# - Installs software on all servers by leveraging the software_management role.

- name: Software Install Playbook
  hosts: all
  become: yes
  vars:
    software_install: true
  roles:
    - role: software_management
