---
# This Ansible playbook updates software and performs group-specific tasks:
#
# - Pulls Docker images using Docker Compose v2 for servers in the docker_servers group.

- name: Pull Docker images using Docker Compose v2
  hosts: docker_servers
  become: yes
  vars:
    docker_pull: true
  roles:
    - role: software_management
