---
# This Ansible playbook performs the following tasks:
# - Executes a distribution upgrade on all servers by leveraging the software_management role.

- name: Software Dist Upgrade Playbook
  hosts: all
  become: yes
  vars:
    software_dist_upgrade: true
  roles:
    - role: software_management

- name: Update Docker Containers
  hosts: docker_servers
  become: yes
  vars:
    check_update_docker_compose: true
  roles:
    - role: docker_management


