---
# This Ansible playbook performs the following tasks:
# - Uninstalls software on all servers by leveraging the software_management role.

- name: Software Uninstall Playbook 
  hosts: all
  become: yes
  vars:
    software_uninstall: true
  roles:
    - role: software_management
