---
# This Ansible playbook updates software and performs group-specific tasks:
# - Updates apt cache and upgrades all packages for all servers.
# - Executes Xen Orchestra update script for servers in the xcp_servers group.
# - Pulls Docker images using Docker Compose v2 for servers in the docker_servers group.

- name: Software Upgrade Playbook
  hosts: all
  become: yes
  vars:
    software_cache: true
    software_upgrade: true
  roles:
    - role: software_management
    
- name: Specific Update tasks for xcp_servers
  hosts: xcp_servers
  become: yes
  vars:
    xen_update: true
  roles:
    - role: software_management

- name: Specific Update tasks for docker_servers
  hosts: docker_servers
  become: yes
  vars:
    docker_pull: true
  roles:
    - role: software_management