---
- hosts: all
  become: true
  tasks:
    - name: Gather and debug system facts
      ansible.builtin.debug:
        msg: |
          System Information:
          -------------------
          Distribution: {{ ansible_lsb.description }}
          Codename: {{ ansible_lsb.codename }}
          Release: {{ ansible_lsb.release }}
          
          Hostname: {{ ansible_hostname }}
          
          Default IPv4:
            Address: {{ ansible_default_ipv4.address }}
            Gateway: {{ ansible_default_ipv4.gateway }}
            Interface: {{ ansible_default_ipv4.interface }}
          
          Memory:
            Total: {{ ansible_memory_mb.real.total }} MB
            Free: {{ ansible_memfree_mb }} MB
          
          Date and Time:
            Current Time: {{ ansible_date_time.date }} {{ ansible_date_time.time }}
            Timezone: {{ ansible_date_time.tz }}
          
          DNS:
            Nameservers: {{ ansible_dns.nameservers | join(', ') }}
          
          Environment:
            Home: {{ ansible_env.HOME }}
            Shell: {{ ansible_env.SHELL }}
            User: {{ ansible_env.USER }}
    
    - name: Capture OS Name
      ansible.builtin.command: uname -a
      register: os_name

    - name: Debug OS Name
      ansible.builtin.debug:
        msg: |
          Operating System Details:
          -------------------------
          {{ os_name.stdout }}
