---
- hosts: all
  become: true # needed for sudo 
  tasks:
  - name: Install Updates 
    tags: 
      - ubuntu
      - always
    apt:
      upgrade: dist
      update_cache: yes # best practice to update cache 
      autoremove: yes
      autoclean: yes
    when: ansible_distribution in ["Debian", "Ubuntu"] #filtering to specific distributions or verisons as other distributions dont use apt 
    

    