---
# roles/webserver/tasks/install.yml

- name: Install Nginx or Apache2
  ansible.builtin.apt:
    name: "{{ item }}"  # Allows multiple packages to be installed using 'item'
    state: present
  with_items:
    - "{{ webserver_package }}"
  notify:
    - Restart web server
  tags:
    - webserver
    - install
    - apt
    - nginx
    - apache2
