---
# roles/webserver/tasks/main.yml

- name: Install web server
  ansible.builtin.include_tasks: install.yml
  tags:
    - webserver
    - install

- name: Copy index.html
  ansible.builtin.include_tasks: copy_index.yml
  tags:
    - webserver
    - copy
    - index

- name: Copy website
  ansible.builtin.include_tasks: copy_website.yml
  tags:
    - webserver
    - copy
    - website

- name: Update website
  ansible.builtin.include_tasks: update_website.yml
  tags:
    - webserver
    - update
    - website

- name: Uninstall web server
  ansible.builtin.include_tasks: uninstall.yml
  tags:
    - webserver
    - uninstall

- name: Tidy up
  ansible.builtin.include_tasks: tidy_up.yml
  tags:
    - webserver
    - tidy_up
