---
# Include individual tasks based on conditions
# Set all to False by default so only run when specifically called  
- name: copy_index
  include_tasks: copy_index.yml
  when: copy_index | default(false)

- name: copy website
  include_tasks: copy_website.yml
  when: copy_website | default(false)

- name: install webserver
  include_tasks: install_webserver.yml
  when: install_webserver | default(false)

- name: tidy up webserver
  include_tasks: tidy_up.yml
  when: tidy_up | default(false)
  
- name: uninstall webserver
  include_tasks: uninstall_webserver.yml
  when: uninstall_webserver | default(false)

- name: update website
  include_tasks: update_website.yml
  when: update_website | default(false)
  
  