# roles/webserver/tasks/uninstall.yml

- name: Uninstall Nginx or Apache2
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ webserver_package }}"
  notify:
    - Stop web server
