# roles/webserver/tasks/update_website.yml

- name: Update website files
  ansible.builtin.synchronize:
    src: roles/webserver/files/website/
    dest: /var/www/html/
  notify:
    - Reload web server
