---
- name: Update repository Index for all hosts
  hosts: all
  become: true
  pre_tasks:
    - name: Update repository index
      tags: 
        - always
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false
      when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]

- hosts: all
  become: true
  roles:
    - base
    - software_updates
    
- hosts: db_servers
  become: true
  roles:
    - db_servers
    
- hosts: docker_servers
  become: true
  roles:
    - docker_servers
    
- hosts: file_servers
  become: true
  roles:
    - file_servers
   
- hosts: web_servers
  become: true
  roles:
    - web_servers
    
- hosts: workstations
  become: true
  roles:
    - workstations
    
- hosts: xcp_servers
  become: true
  roles:
    - xcp_servers
