---
- name: Test using ansible vault
  hosts: localhost
  vars_files:
    - demo_vault.yml
  tasks:
    - name: Show the secret
      ansible.builtin.debug:
        msg: "The secret password is {{ my_secret }}"
