---
- hosts: all
  become: true
  tasks:
    - name: Install Updates 
      tags: 
        - ubuntu
        - always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
        autoremove: yes
        autoclean: yes
      when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]
