---
# Include individual tasks based on conditions
- include_tasks: disable_ipv6.yml
  when: disable_ipv6 | default(false)

- include_tasks: set_timezone.yml
  when: set_timezone | default(false)

- include_tasks: swap_file.yml
  when: swap_file | default(false)
  