---
# tasks file for setting_timezone

- name: Check the current timezone
  ansible.builtin.command: 
    cmd: timedatectl show -p Timezone --value
  register: current_timezone
  tags:
    - timezone
    - check

- name: Set timezone
  ansible.builtin.command: 
    cmd: timedatectl set-timezone {{ timezone }}
  when: current_timezone.stdout != timezone
  tags:
    - timezone
    - set
