---
# tasks file for creating multiple users with home folders and adding them to groups

- name: Create new users with home folders
  ansible.builtin.user:
    name: "{{ item.name }}"
    home: "{{ item.home }}"
    create_home: yes
    state: present
    groups: "{{ item.groups }}"
  loop: "{{ users }}"
  tags:
    - user_management
    - create_user

- name: Set ownership and permissions of home folders
  ansible.builtin.file:
    path: "{{ item.home }}"
    owner: "{{ item.name }}"
    group: "sudo"  # Set primary group to sudo
    mode: '0755'
  loop: "{{ users }}"
  when: create_user
  tags:
    - user_management
    - set_permissions
