---
# Include individual tasks based on conditions
# Set all to False by default so only run when specifically called  
- name: assign groups
  include_tasks: assign_groups.yml
  when: assign_groups | default(false)

- name: create user 
  include_tasks: create_user.yml
  when: create_user | default(false)

- name: delete user
  include_tasks: delete_user.yml
  when: delete_user | default(false)

- name: make sudoer
  include_tasks: make_sudoer.yml
  when: make_sudoer | default(false)
  
  