---
- name: Make users sudoers by creating files in sudoers.d 
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ item.name }}"
    content: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
    owner: root
    group: root
    mode: '0440'
  when: item.sudoer and make_sudoer | bool
  loop: "{{ users }}"
  tags:
    - user_management
    - make_sudoer
