---
# tasks file for making the user a sudoer
 - name: Make user a sudoer
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ item.name }}"
    line: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
    state: present
  validate: 'visudo -cf %s'
  when: item.sudoer | default(False)

- name: Set permissions on sudoers file
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ item.name }}"
    owner: root
    group: root
    mode: '0440'
  when: item.sudoer | default(False)
