---
# Pull clean repositories
- name: Pull clean repositories
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ item.path }}"
    update: yes
  loop: "{{ git_repositories }}"
  when: git_pull_clean and git_status_clean[item.name]
  become: yes
  become_user: paul
  environment:
    HOME: "/home/paul"
    XDG_CONFIG_HOME: "/home/paul/.config"
