---
# Report dirty repositories
- name: Report dirty repositories
  ansible.builtin.debug:
    msg: "Repository {{ item.name }} has uncommitted changes!"
  loop: "{{ git_repositories }}"
  when: git_report_dirty and not git_status_clean[item.name]
