---
- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: '0700'
  become: yes

- name: Generate RSA key
  command: ssh-keygen -t rsa -b {{ rsa_key_size }} -f {{ ansible_user_dir }}/.ssh/id_rsa -N ""
  args:
    creates: "{{ ansible_user_dir }}/.ssh/id_rsa"
  become: yes

- name: Generate ED25519 key
  command: ssh-keygen -t ed25519 -b {{ ed25519_key_size }} -f {{ ansible_user_dir }}/.ssh/id_ed25519 -N ""
  args:
    creates: "{{ ansible_user_dir }}/.ssh/id_ed25519"
  become: yes
