---
# Include individual tasks based on conditions
- include_tasks: backup_keys.yml
  when: backup_keys | default(false)

- include_tasks: create_keys.yml
  when: create_keys | default(false)

- include_tasks: delete_backups.yml
  when: delete_backups | default(false)
  