---
# Include individual tasks based on conditions
# Set all to False by default so only run when specifically called  
- name: backup keys
  include_tasks: backup_keys.yml
  when: backup_keys | default(false)

- name: create keys
  include_tasks: create_keys.yml
  when: create_keys | default(false)

- name: delete backup
  include_tasks: delete_backups.yml
  when: delete_backups | default(false)
  