---
# tasks file for managing apt cache

- name: Ensure update cache is up to date
  community.general.aptitude:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution in ["Debian", "Ubuntu"]  # Filtering to specific distributions as other distributions don't use apt
  tags:
    - apt
    - update

- name: Ensure autoclean is set
  community.general.aptitude:
    autoclean: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]  # Filtering to specific distributions as other distributions don't use apt
  tags:
    - apt
    - autoclean

- name: Ensure autoremove is set
  community.general.aptitude:
    autoremove: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]  # Filtering to specific distributions as other distributions don't use apt
  tags:
    - apt
    - autoremove


