---
- name: Ensure update cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution in ["Debian", "Ubuntu"] #filtering to specific distributions or verisons as other distributions dont use apt 

- name: Ensure autoclean is set
  apt:
    autoclean: yes
  when: ansible_distribution in ["Debian", "Ubuntu"] #filtering to specific distributions or verisons as other distributions dont use apt 

- name: Ensure autoremove is set
  apt:
    autoremove: yes
  when: ansible_distribution in ["Debian", "Ubuntu"] #filtering to specific distributions or verisons as other distributions dont use apt 
