---
# tasks file for aptitude_software_install

- name: Install software packages
  become: yes
  ansible.builtin.aptitude:
    name: "{{ item }}"
    state: latest
  loop: "{{ software_list }}"
  tags:
    - aptitude
    - software_install
