---
# Include individual tasks based on conditions
# Set all to False by default so only run when specifically called  
- name: Include software_cache tasks
  include_tasks: software_cache.yml
  when: software_cache | default(false)
 
- name: Include software_install tasks
  include_tasks: software_install.yml
  when: software_install | default(false)
 
- name: Include software_uninstall tasks
  include_tasks: software_uninstall.yml
  when: software_uninstall | default(false)
 
- name: Include software_upgrade tasks
  include_tasks: software_upgrade.yml
  when: software_upgrade | default(false)
  
- name: Include software_dist_upgrade tasks
  include_tasks: software_dist_upgrade.yml
  when: software_dist_upgrade | default(false)
 