---
# Include individual tasks based on conditions
- include_tasks: software_cache.yml
  when: software_cache | default(false)

- include_tasks: software_install.yml
  when: software_install | default(false)

- include_tasks: software_uninstall.yml
  when: software_uninstall | default(false)
  
- include_tasks: software_upgrade.yml
  when: software_upgrade | default(false)
  
- include_tasks: software_dist_upgrade.yml
  when: software_dist_upgrade | default(false)
  
- include_tasks: xen_update.yml
  when: xen_update | default(false)
  
- include_tasks: docker_pull.yml
  when: docker_pull | default(false)
  
 
