---
# tasks file for safe_upgrade role

- name: Ensure aptitude is installed
  ansible.builtin.apt:
    name: aptitude
    state: present
    update_cache: yes
    autoremove: yes
    autoclean: yes
    cache_valid_time: 3600
  when: ansible_distribution in ["Debian", "Ubuntu"]
  tags:
    - safe_upgrade
    - aptitude
    - install

- name: Check if any upgrades are available using apt-get
  ansible.builtin.command:
    cmd: apt-get -s dist-upgrade
  register: upgrade_check
  changed_when: false
  check_mode: no
  tags:
    - safe_upgrade
    - check

- name: Set upgrade_required fact
  ansible.builtin.set_fact:
    upgrade_required: "{{ 'The following packages will be upgraded:' in upgrade_check.stdout }}"
  tags:
    - safe_upgrade
    - set_fact

- name: Print upgradeable packages only if there are updates
  ansible.builtin.debug:
    msg: "{{ upgrade_check.stdout_lines }}"
  when: upgrade_required
  tags:
    - safe_upgrade
    - debug

- name: Upgrade all packages using aptitude
  ansible.builtin.command:
    cmd: aptitude safe-upgrade -y
  when: upgrade_required
  tags:
    - safe_upgrade
    - upgrade
