- name: Perform dist-upgrade
  apt:
    upgrade: dist
    update_cache: yes

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Set reboot required fact
  set_fact:
    reboot_required: "{{ reboot_required_file.stat.exists }}"

- name: Reboot if necessary
  reboot:
  when: reboot_required
