- name: Uninstall software packages
  become: yes
  community.general.aptitude:
    name: "{{ item }}"
    state: absent
  loop: "{{ software_uninstall_list }}"
  tags:
    - software
    - uninstall
    - aptitude
