---
# Uninstall software(s) on Debian-based and Red Hat-based distros
- name: Uninstall software on Debian-based distros
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ software_uninstall_list }}"
  when:
    - ansible_facts['os_family'] == "Debian"
    - software_uninstall_list is defined
    - software_uninstall_list | length > 0

- name: Uninstall software on Red Hat-based distros with yum
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ software_uninstall_list }}"
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_distribution_major_version | int < 8
    - software_uninstall_list is defined
    - software_uninstall_list | length > 0

- name: Uninstall software on Red Hat-based distros with dnf
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
  with_items: "{{ software_uninstall_list }}"
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_distribution_major_version | int >= 8
    - software_uninstall_list is defined
    - software_uninstall_list | length > 0
