---
# tasks file for software_install

- name: Install software packages
  become: yes
  community.general.aptitude:
    name: "{{ item }}"
    state: latest
  loop: "{{ software_list }}"
  tags:
    - software
    - install
    - apt
