<<<<<<< HEAD
---
- name: Install software packages
  become: yes
  aptitude:
    name: "{{ item }}"
    state: absent
  loop: "{{ software_uninstall_list }}"
=======
---
# roles/safe_upgrade/tasks/software_uninstall.yml
- name: Uninstall software packages
  become: yes
  ansible.builtin.aptitude:
    name: "{{ item }}"
    state: absent
  loop: "{{ software_uninstall_list }}"
>>>>>>> 3370257 (updates)
