<<<<<<< HEAD
---
- name: Install software packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ software_list }}"
=======
---
# roles/safe_upgrade/tasks/software_install.yml
- name: Install software packages
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ software_list }}"
>>>>>>> 3370257 (updates)
