---
# tasks file for software_uninstall

- name: Uninstall software packages
  become: yes
  ansible.builtin.aptitude:
    name: "{{ item }}"
    state: absent
  loop: "{{ software_uninstall_list }}"
  tags:
    - software
    - uninstall
    - aptitude
