---
# main.yaml for base/ all servers  

- name: add ssh key usr_ansible
  tags: always
  authorized_key:
    user: usr_ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJS321RVYEcDx3OdOiSe+YZSE3h0/RNemdRXUeGSWc99 ansible"
    
- name: Update and upgrade APT packages 
  tags: always
  apt: 
    update_cache: yes 
    upgrade: dist
    autoremove: yes
  when: ansible_distribution in ["Debian", "Ubuntu"] #filtering to specific distributions or verisons as other distributions dont use apt 
      
- name: Install aptitude and cockpit
  tags: ubuntu,aptitude,cockpit
  apt:
    name: 
      - aptitude
      - cockpit
    state: latest
    update_cache: yes # best practice to update cache 
  when: ansible_distribution in ["Debian", "Ubuntu"] #filtering to specific distributions or verisons as other distributions dont use apt 