---
# tasks file for db_servers

- name: Install PostgreSQL
  tags: 
    - ubuntu
    - db
    - postgresql
  ansible.builtin.apt:
    name: postgresql
    state: latest
  when: 
    - ansible_distribution in ["Debian", "Ubuntu"]  # Filtering to specific distributions or versions as other distributions don't use apt

- name: Ensure PostgreSQL has started 
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true
  tags:
    - ubuntu
    - db
    - postgresql
