# roles/webserver/handlers/main.yml

- name: Start web server
  ansible.builtin.service:
    name: "{{ webserver_service }}"
    state: started

- name: Stop web server
  ansible.builtin.service:
    name: "{{ webserver_service }}"
    state: stopped

- name: Restart web server
  ansible.builtin.service:
    name: "{{ webserver_service }}"
    state: restarted

- name: Reload web server
  ansible.builtin.service:
    name: "{{ webserver_service }}"
    state: reloaded
